name: Build
on: [push]
jobs: 
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run black
        run: black --check .

  test: 
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/*.py

  deploy-to-impaas:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ImPaaS-Deploy
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: sse-groupwork1
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM
      - name: Notify on Failure
        if: failure()
        uses: impaas/impaas-notify@v2
        with:
          app-name: sse-groupwork1
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          message: |
            Build failed






'''


  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.12"
  REQUIREMENTS_FILE: "requirements.txt"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy:
    name: Deploy to Production
    needs: tests
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.REQUIREMENTS_FILE }}
        
      - name: Deploy to ImPaaS
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: sse-groupwork1
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM
'''