name: Python CI/CD Pipeline
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.12"
  REQUIREMENTS_FILE: "requirements.txt"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy:
    name: Deploy to Production
    #needs: [unit-tests, integration-tests, system-tests]
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.REQUIREMENTS_FILE }}
        
      - name: Deploy to ImPaaS
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: sse-groupwork1
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM
