name: Python CI/CD Pipeline

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
      name: Run Tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Unit Tests
          run: |
            pytest --junitxml=unit-results.xml --cov=. --cov-report=xml:unit-coverage.xml

        - name: Upload Unit Test Results
          uses: actions/upload-artifact@v3
          with:
            name: unit-test-results
            path: unit-results.xml

        - name: Upload Unit Test Coverage Results
          uses: actions/upload-artifact@v3
          with:
            name: unit-coverage-report
            path: unit-coverage.xml

        - name: Run Integration Tests
          run: |
            pytest tests/integration --junitxml=integration-results.xml --cov=. --cov-report=xml:integration-coverage.xml

        - name: Upload Integration Test Results
          uses: actions/upload-artifact@v3
          with:
            name: integration-test-results
            path: integration-results.xml

        - name: Upload Integration Test Coverage Results
          uses: actions/upload-artifact@v3
          with:
            name: integration-coverage-report
            path: integration-coverage.xml

        - name: Run System Tests
          run: |
            pytest tests/system --junitxml=system-results.xml --cov=. --cov-report=xml:system-coverage.xml

        - name: Upload System Test Results          
          uses: actions/upload-artifact@v3
          with:
            name: system-test-results
            path: system-results.xml

        - name: Upload System Test Coverage Results
          uses: actions/upload-artifact@v3
          with:
            name: system-coverage-report
            path: system-coverage.xml

  deploy:
    name: Deploy to Production
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Deploy to ImPaaS
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: sse-groupwork1
          deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
          method: PLATFORM