name: Build
on: [push]

jobs: 
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
        if: ${{ success() }}

  test: 
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/*.py

  deploy-to-impaas:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ImPaaS-Deploy
        uses: /impaas/impaas-deploy@v3
        with:
          app-name: sse-groupwork1
          deployment-token: ${{secrets.IMPAAS_DEPLOY_TOKEN}}
          method: PLATFORM
